# Generated by Django 4.2.4 on 2023-08-16 04:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='immutable id', primary_key=True, serialize=False, verbose_name='file id'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='immutable id', primary_key=True, serialize=False, verbose_name='folder id'),
        ),
    ]
