# Generated by Django 4.2.4 on 2023-08-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_file_options_folder_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(help_text='Required and unique', max_length=50, verbose_name='Folder Name'),
        ),
    ]
