# Generated by Django 4.2.4 on 2023-08-31 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_folder_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='is_published',
        ),
    ]
